[package]
name = "vrpn"
version = "0.1.0"
authors = ["Ryan Pavlik <ryan.pavlik@collabora.com>"]
license = "BSL-1.0"
edition = "2018"
description = "A port of the VRPN (Virtual Reality Peripheral Network) protocol to async code in Rust"
repository = "https://github.com/vrpn/vrpn-rs"
readme = "README.md"

[dependencies]
bytes = "0.4.10"
bitmask = "0.4.0"
cgmath = "0.16.1"
quick-error = "1.2.2"
downcast-rs = "1.0.3"
mio = "0.6.16"
tokio = "0.1.11"
tk-listen = "0.2.0"
socket2 = "0.3.8"
futures = "0.1.25"
chrono = "0.4.6"
url = "1.7.2"

[dev-dependencies]
quickcheck = "0.7.2"
hex-literal = "0.1.1"
